-- =====================================================
-- Update Monthly Maintenance Amount for June 2026
-- Source: eSociety_BillRegister1_11122025
-- =====================================================

SET SQL_SAFE_UPDATES = 0;

-- C Wing
UPDATE units SET monthly_maintenance_amount = 3265 WHERE unit_number = 'C-101';
UPDATE units SET monthly_maintenance_amount = 3425 WHERE unit_number = 'C-102';
UPDATE units SET monthly_maintenance_amount = 3739 WHERE unit_number = 'C-103';
UPDATE units SET monthly_maintenance_amount = 3285 WHERE unit_number = 'C-104';
UPDATE units SET monthly_maintenance_amount = 3418 WHERE unit_number = 'C-105';
UPDATE units SET monthly_maintenance_amount = 3291 WHERE unit_number = 'C-106';
UPDATE units SET monthly_maintenance_amount = 3269 WHERE unit_number = 'C-201';
UPDATE units SET monthly_maintenance_amount = 3209 WHERE unit_number = 'C-202';
UPDATE units SET monthly_maintenance_amount = 3663 WHERE unit_number = 'C-203';
UPDATE units SET monthly_maintenance_amount = 3335 WHERE unit_number = 'C-204';
UPDATE units SET monthly_maintenance_amount = 3321 WHERE unit_number = 'C-205';
UPDATE units SET monthly_maintenance_amount = 3321 WHERE unit_number = 'C-206';
UPDATE units SET monthly_maintenance_amount = 3219 WHERE unit_number = 'C-301';
UPDATE units SET monthly_maintenance_amount = 3249 WHERE unit_number = 'C-302';
UPDATE units SET monthly_maintenance_amount = 3745 WHERE unit_number = 'C-303';
UPDATE units SET monthly_maintenance_amount = 3267 WHERE unit_number = 'C-304';
UPDATE units SET monthly_maintenance_amount = 3314 WHERE unit_number = 'C-305';
UPDATE units SET monthly_maintenance_amount = 3714 WHERE unit_number = 'C-306';
UPDATE units SET monthly_maintenance_amount = 3374 WHERE unit_number = 'C-401';
UPDATE units SET monthly_maintenance_amount = 3265 WHERE unit_number = 'C-402';
UPDATE units SET monthly_maintenance_amount = 3723 WHERE unit_number = 'C-403';
UPDATE units SET monthly_maintenance_amount = 3346 WHERE unit_number = 'C-404';
UPDATE units SET monthly_maintenance_amount = 3416 WHERE unit_number = 'C-405';
UPDATE units SET monthly_maintenance_amount = 3414 WHERE unit_number = 'C-406';
UPDATE units SET monthly_maintenance_amount = 3360 WHERE unit_number = 'C-501';
UPDATE units SET monthly_maintenance_amount = 3269 WHERE unit_number = 'C-502';
UPDATE units SET monthly_maintenance_amount = 3663 WHERE unit_number = 'C-503';
UPDATE units SET monthly_maintenance_amount = 3376 WHERE unit_number = 'C-504';
UPDATE units SET monthly_maintenance_amount = 3414 WHERE unit_number = 'C-505';
UPDATE units SET monthly_maintenance_amount = 3322 WHERE unit_number = 'C-506';
UPDATE units SET monthly_maintenance_amount = 3279 WHERE unit_number = 'C-601';
UPDATE units SET monthly_maintenance_amount = 3249 WHERE unit_number = 'C-602';
UPDATE units SET monthly_maintenance_amount = 3783 WHERE unit_number = 'C-603';
UPDATE units SET monthly_maintenance_amount = 3501 WHERE unit_number = 'C-604';
UPDATE units SET monthly_maintenance_amount = 3259 WHERE unit_number = 'C-605';
UPDATE units SET monthly_maintenance_amount = 3259 WHERE unit_number = 'C-606';
UPDATE units SET monthly_maintenance_amount = 3269 WHERE unit_number = 'C-701';
UPDATE units SET monthly_maintenance_amount = 3209 WHERE unit_number = 'C-702';
UPDATE units SET monthly_maintenance_amount = 3783 WHERE unit_number = 'C-703';
UPDATE units SET monthly_maintenance_amount = 3490 WHERE unit_number = 'C-704';
UPDATE units SET monthly_maintenance_amount = 3262 WHERE unit_number = 'C-705';
UPDATE units SET monthly_maintenance_amount = 3289 WHERE unit_number = 'C-706';
UPDATE units SET monthly_maintenance_amount = 3249 WHERE unit_number = 'C-802';
UPDATE units SET monthly_maintenance_amount = 3723 WHERE unit_number = 'C-803';
UPDATE units SET monthly_maintenance_amount = 3286 WHERE unit_number = 'C-804';
UPDATE units SET monthly_maintenance_amount = 3259 WHERE unit_number = 'C-805';
UPDATE units SET monthly_maintenance_amount = 3417 WHERE unit_number = 'C-806';
UPDATE units SET monthly_maintenance_amount = 3279 WHERE unit_number = 'C-901';
UPDATE units SET monthly_maintenance_amount = 3205 WHERE unit_number = 'C-902';
UPDATE units SET monthly_maintenance_amount = 3667 WHERE unit_number = 'C-903';
UPDATE units SET monthly_maintenance_amount = 3286 WHERE unit_number = 'C-904';
UPDATE units SET monthly_maintenance_amount = 3262 WHERE unit_number = 'C-905';
UPDATE units SET monthly_maintenance_amount = 3351 WHERE unit_number = 'C-906';
UPDATE units SET monthly_maintenance_amount = 3269 WHERE unit_number = 'C-1001';
UPDATE units SET monthly_maintenance_amount = 3239 WHERE unit_number = 'C-1002';
UPDATE units SET monthly_maintenance_amount = 4378 WHERE unit_number = 'C-1003';
UPDATE units SET monthly_maintenance_amount = 3316 WHERE unit_number = 'C-1004';
UPDATE units SET monthly_maintenance_amount = 3291 WHERE unit_number = 'C-1005';
UPDATE units SET monthly_maintenance_amount = 3289 WHERE unit_number = 'C-1006';
UPDATE units SET monthly_maintenance_amount = 3360 WHERE unit_number = 'C-1101';
UPDATE units SET monthly_maintenance_amount = 3205 WHERE unit_number = 'C-1102';
UPDATE units SET monthly_maintenance_amount = 3882 WHERE unit_number = 'C-1103';
UPDATE units SET monthly_maintenance_amount = 3430 WHERE unit_number = 'C-1104';
UPDATE units SET monthly_maintenance_amount = 3819 WHERE unit_number = 'C-1105';
UPDATE units SET monthly_maintenance_amount = 3819 WHERE unit_number = 'C-1106';
UPDATE units SET monthly_maintenance_amount = 3209 WHERE unit_number = 'C-1202';
UPDATE units SET monthly_maintenance_amount = 3735 WHERE unit_number = 'C-1203';
UPDATE units SET monthly_maintenance_amount = 3501 WHERE unit_number = 'C-1204';
UPDATE units SET monthly_maintenance_amount = 3349 WHERE unit_number = 'C-1205';
UPDATE units SET monthly_maintenance_amount = 3759 WHERE unit_number = 'C-1206';
UPDATE units SET monthly_maintenance_amount = 3205 WHERE unit_number = 'C-1301';
UPDATE units SET monthly_maintenance_amount = 3235 WHERE unit_number = 'C-1302';
UPDATE units SET monthly_maintenance_amount = 3727 WHERE unit_number = 'C-1303';
UPDATE units SET monthly_maintenance_amount = 3395 WHERE unit_number = 'C-1304';
UPDATE units SET monthly_maintenance_amount = 3292 WHERE unit_number = 'C-1305';
UPDATE units SET monthly_maintenance_amount = 3414 WHERE unit_number = 'C-1306';
UPDATE units SET monthly_maintenance_amount = 3235 WHERE unit_number = 'C-1401';
UPDATE units SET monthly_maintenance_amount = 3360 WHERE unit_number = 'C-1402';
UPDATE units SET monthly_maintenance_amount = 3882 WHERE unit_number = 'C-1403';
UPDATE units SET monthly_maintenance_amount = 3327 WHERE unit_number = 'C-1404';
UPDATE units SET monthly_maintenance_amount = 3292 WHERE unit_number = 'C-1405';
UPDATE units SET monthly_maintenance_amount = 3284 WHERE unit_number = 'C-1406';

-- D Wing
UPDATE units SET monthly_maintenance_amount = 3194 WHERE unit_number = 'D-101';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-102';
UPDATE units SET monthly_maintenance_amount = 2871 WHERE unit_number = 'D-103';
UPDATE units SET monthly_maintenance_amount = 2841 WHERE unit_number = 'D-104';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-105';
UPDATE units SET monthly_maintenance_amount = 3225 WHERE unit_number = 'D-106';
UPDATE units SET monthly_maintenance_amount = 3254 WHERE unit_number = 'D-201';
UPDATE units SET monthly_maintenance_amount = 3254 WHERE unit_number = 'D-202';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-203';
UPDATE units SET monthly_maintenance_amount = 3186 WHERE unit_number = 'D-204';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-205';
UPDATE units SET monthly_maintenance_amount = 3229 WHERE unit_number = 'D-206';
UPDATE units SET monthly_maintenance_amount = 3259 WHERE unit_number = 'D-301';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-302';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-303';
UPDATE units SET monthly_maintenance_amount = 3386 WHERE unit_number = 'D-304';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-305';
UPDATE units SET monthly_maintenance_amount = 3225 WHERE unit_number = 'D-306';
UPDATE units SET monthly_maintenance_amount = 3224 WHERE unit_number = 'D-401';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-402';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-403';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-404';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-405';
UPDATE units SET monthly_maintenance_amount = 3199 WHERE unit_number = 'D-406';
UPDATE units SET monthly_maintenance_amount = 3354 WHERE unit_number = 'D-501';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-502';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-503';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-504';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-505';
UPDATE units SET monthly_maintenance_amount = 3350 WHERE unit_number = 'D-506';
UPDATE units SET monthly_maintenance_amount = 3229 WHERE unit_number = 'D-601';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-602';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-603';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-604';
UPDATE units SET monthly_maintenance_amount = 3232 WHERE unit_number = 'D-605';
UPDATE units SET monthly_maintenance_amount = 3199 WHERE unit_number = 'D-606';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-701';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-702';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-703';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-704';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-705';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-706';
UPDATE units SET monthly_maintenance_amount = 3354 WHERE unit_number = 'D-801';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-802';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-803';
UPDATE units SET monthly_maintenance_amount = 3195 WHERE unit_number = 'D-804';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-805';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-901';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-902';
UPDATE units SET monthly_maintenance_amount = 3255 WHERE unit_number = 'D-903';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-904';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-905';
UPDATE units SET monthly_maintenance_amount = 3259 WHERE unit_number = 'D-906';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1001';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1002';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1003';
UPDATE units SET monthly_maintenance_amount = 3195 WHERE unit_number = 'D-1004';
UPDATE units SET monthly_maintenance_amount = 3354 WHERE unit_number = 'D-1005';
UPDATE units SET monthly_maintenance_amount = 3414 WHERE unit_number = 'D-1006';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1101';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-1102';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-1103';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1104';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-1105';
UPDATE units SET monthly_maintenance_amount = 3354 WHERE unit_number = 'D-1106';
UPDATE units SET monthly_maintenance_amount = 3261 WHERE unit_number = 'D-1201';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1202';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-1203';
UPDATE units SET monthly_maintenance_amount = 3350 WHERE unit_number = 'D-1204';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1205';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-1301';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1302';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1303';
UPDATE units SET monthly_maintenance_amount = 3195 WHERE unit_number = 'D-1304';
UPDATE units SET monthly_maintenance_amount = 3356 WHERE unit_number = 'D-1305';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-1306';
UPDATE units SET monthly_maintenance_amount = 3231 WHERE unit_number = 'D-1401';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1402';
UPDATE units SET monthly_maintenance_amount = 3201 WHERE unit_number = 'D-1403';
UPDATE units SET monthly_maintenance_amount = 3195 WHERE unit_number = 'D-1404';
UPDATE units SET monthly_maintenance_amount = 3386 WHERE unit_number = 'D-1405';
UPDATE units SET monthly_maintenance_amount = 3416 WHERE unit_number = 'D-1406';

-- Shops
UPDATE units SET monthly_maintenance_amount = 2737 WHERE unit_number = 'S-0024';
UPDATE units SET monthly_maintenance_amount = 2731 WHERE unit_number = 'S-0025';
UPDATE units SET monthly_maintenance_amount = 2793 WHERE unit_number = 'S-0026';
UPDATE units SET monthly_maintenance_amount = 2739 WHERE unit_number = 'S-0027';
UPDATE units SET monthly_maintenance_amount = 2870 WHERE unit_number = 'S-0028';
UPDATE units SET monthly_maintenance_amount = 2880 WHERE unit_number = 'S-0029';
UPDATE units SET monthly_maintenance_amount = 2765 WHERE unit_number = 'S-0030';
UPDATE units SET monthly_maintenance_amount = 2912 WHERE unit_number = 'S-0031';
UPDATE units SET monthly_maintenance_amount = 2878 WHERE unit_number = 'S-0032';
UPDATE units SET monthly_maintenance_amount = 2862 WHERE unit_number = 'S-0033';
UPDATE units SET monthly_maintenance_amount = 2861 WHERE unit_number = 'S-0034';
UPDATE units SET monthly_maintenance_amount = 2884 WHERE unit_number = 'S-0035';
UPDATE units SET monthly_maintenance_amount = 1765 WHERE unit_number = 'S-0036';
UPDATE units SET monthly_maintenance_amount = 2881 WHERE unit_number = 'S-0037';

SET SQL_SAFE_UPDATES = 1;

-- Verify
SELECT unit_number, monthly_maintenance_amount 
FROM units 
WHERE wing IN ('C', 'D') OR unit_number LIKE 'S-%'
ORDER BY wing, unit_number;
