package com.society.enums;

public enum ExpenseCategory {
    SECURITY,
    HOUSEKEEPING,
    ELECTRICITY_COMMON,
    WATER,
    LIFT_MAINTENANCE,
    GARDEN,
    REPAIRS_MAINTENANCE,
    PEST_CONTROL,
    LEGAL_PROFESSIONAL,
    STATIONERY_PRINTING,
    EVENTS_CELEBRATIONS,
    INSURANCE,
    SINKING_FUND,
    BANK_CHARGES,
    MAINTENANCE_INCOME,
    INTEREST_INCOME,
    PENALTY_INCOME,
    MISCELLANEOUS
}
